development:
  adapter: postgresql
  encoding: unicode
  database: cattube_development
  pool: 5
  host: postgres
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: cattube_test
  pool: 5
  username: myapp
  password: password1
